name: Rebuild Secure Base Image Weekly

on:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2:00 AM UTC
  workflow_dispatch:     # Allow manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Secure Base Image
        uses: docker/build-push-action@v5
        with:
          context: ./secure-base
          push: true
          tags: |
           ghcr.io/swalia-proj/secure-base:latest
           ghcr.io/swalia-proj/secure-base:${{ github.run_id }}
